bbsnote/urls.py
from django.urls import path
from . import views

app_name = 'bbsnote'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('comment/create/<int:board_id>/', views.comment_create, name='comment_create'),
    path('board/create/', views.board_create, name='board_create'),
    
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views #현재 있는 얘로부터 views를  import한다 

app_name='common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), #login 요청이 들어오면~
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), #로그아웃은 그냥 메소드 호출만 하고 종료 
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bbsnote import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbsnote/', include('bbsnote.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'), #아무것도 없으면 index정보로 가라
    
]

bbsnote/models.py
from django.db import models

# Create your models here.
class Board(models.Model): #게시글 모델
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Comment(models.Model): #댓글 모델
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

common/models.py
from django.db import models

# Create your models here.

bbsnote/forms.py
from django import forms
from bbsnote.models import Board

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['subject', 'content']

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")
        

bbsnote/views.py
from django.core import paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse #http 요청을 받으면 반응하는 도구
from .models import Board, Comment
from django.utils import timezone
from .forms import BoardForm
from django.core.paginator import Paginator

# Create your views here.
def index(request): #페이징 기능 추가 
    page = request.GET.get('page', 1)
    #return HttpResponse("bbsnote에 오신것을 환영합니다. ");
    board_list = Board.objects.order_by('-create_date')

    #페이징 처리    
    paginator = Paginator(board_list, 5)
    page_obj = paginator.get_page(page)

    context = {'board_list' :  page_obj} #딕셔너리로 선언
    return render(request, 'bbsnote/board_list.html', context) #board_list.html 요청이 들어오면 context를 바인딩 해줘라
    #쿼리문은 사용하지 않았지만 스프링에서 select를 사용한것과 비슷함 

def detail(request, board_id):
    board = Board.objects.get(id=board_id)
    context = {'board' : board}
    return render(request, 'bbsnote/board_detail.html', context)

def comment_create(request, board_id):
    board = Board.objects.get(id=board_id)
    # comment = Comment(board=board, content=request.POST.get('content'), create_date=timezone.now())
    # comment.save()
    board.comment_set.creat(content=request.POST.get('content'), create_date=timezone.now()) #comment.set을 사용해서 위에와 동일하게 할수도 있다
    return redirect('bbsnote:detail', board_id=board.id)
    
def board_create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.create_date = timezone.now()
            board.save()
            return redirect('bbsnote:index')
    else: #get방식으로 호출이 되면 
        form = BoardForm() #BoardForm방식으로 호출을 해라 
    return render(request, 'bbsnote/board_form.html', {'form':form}) #그리고 여기 주소로 보내고 form 데이터를 form으로 넘긴다 

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from .forms import UserForm

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password) #앞에서 받은 username, password를 받아서 인증정보를 authenticate을 통해 인증체크를 해줌
            login(request, user) #그 체크한게 문제가 없으면 자동로그인을 해줌
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>게시판 노트</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>
</html> 

templates/bbsnote/board_detail.html
<h1>{{board.subject}}</h1>
<div>
    {{board.content}}
</div>



<h5>{{board.comment_set.count}}개의 댓글이 있습니다.</h5>
<div>
    <ul>
        {% for comment in board.comment_set.all%}
            <li>{{comment.content}}</li>
        {% endfor%}
    </ul>
</div>
<form action="{% url 'bbsnote:comment_create' board.id %}" method="post">
{% csrf_token%}
<textarea name="content" id="content" rows="15"></textarea>
<input type="submit" value="댓글달기">
</form>

templates/bbsnote/board_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token%}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{%endblock%}

templates/bbsnote/board_list.html
{% extends 'base.html' %} <!-- base.html을 상속받음 -->
{% load bbsnote_filter %} <!--만든 빼기 기능을 넣어줌 -->
{% block content %}
<div class="container my-3">
    <table class="table"> <!--부트스트랩에서 기본적으로 제공하는 클래스 -->
        <thead>
        <tr class="text-center thead-dark"> 
            <th></th>           
            <th style="width:50%">제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board_list %}
            {% for board in board_list %}
            <tr class="text-center">
                <td>{{board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1}}</td>
                <td class="text-left">
                    <a href="{% url 'bbsnote:detail' board.id %}">{{ board.subject }}</a>                
                </td>            
                <td>{{ board.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table> 

        <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board_list.has_previous %} <!--이전 페이지가 있으면 -->
        <li class="page-item"> 
            <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a> <!--이전 페이지가 있으면 링크를 걸어줌-->
        </li>
        {% else %} <!--이전 페이지가 없으면  -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a> <!--이전 페이지가 없으면 링크를 걸어주지 않음 -->
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %} <!--현재 페이지 기준으로 좌우로 5개씩 더해줘라 = 페이지가 많아지면 글자가 가운데로 감-->
            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    
        <a href="{% url 'bbsnote:board_create' %}" class="btn btn-primary">등록</a>
    </div>
    <form id="searchForm" method="get" action="{% url 'index' %}">   <!--현재페이지(=index)-->
        <input type="hidden" id="page" name="page" value="{{ page }}">    
    </form>
    {% endblock %}
    {% block script %}
    <script type='text/javascript'>
    $(document).ready(function(){
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });     
    });
    </script>
{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content  %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html"  %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock  %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:''  }}"> <!--/ 데이터에서 넘어오는 값이 없으면 그냥 ''으로 해줌-->
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:''  }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}